//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItWebApp.ArgumentResolverService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArgumentResolverService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ResolveArgument", ReplyAction="http://tempuri.org/IService1/ResolveArgumentResponse")]
        string ResolveArgument(string argument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ResolveArgument", ReplyAction="http://tempuri.org/IService1/ResolveArgumentResponse")]
        System.Threading.Tasks.Task<string> ResolveArgumentAsync(string argument);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItWebApp.ArgumentResolverService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItWebApp.ArgumentResolverService.IService1>, TryItWebApp.ArgumentResolverService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ResolveArgument(string argument) {
            return base.Channel.ResolveArgument(argument);
        }
        
        public System.Threading.Tasks.Task<string> ResolveArgumentAsync(string argument) {
            return base.Channel.ResolveArgumentAsync(argument);
        }
    }
}
