//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItWebApp.PasswordStrengthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordFeedback", Namespace="http://schemas.datacontract.org/2004/07/PasswordStrengthService")]
    [System.SerializableAttribute()]
    public partial class PasswordFeedback : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] IssuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrengthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Issues {
            get {
                return this.IssuesField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesField, value) != true)) {
                    this.IssuesField = value;
                    this.RaisePropertyChanged("Issues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Strength {
            get {
                return this.StrengthField;
            }
            set {
                if ((object.ReferenceEquals(this.StrengthField, value) != true)) {
                    this.StrengthField = value;
                    this.RaisePropertyChanged("Strength");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PasswordStrengthService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckStrength", ReplyAction="http://tempuri.org/IService1/CheckStrengthResponse")]
        TryItWebApp.PasswordStrengthService.PasswordFeedback CheckStrength(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckStrength", ReplyAction="http://tempuri.org/IService1/CheckStrengthResponse")]
        System.Threading.Tasks.Task<TryItWebApp.PasswordStrengthService.PasswordFeedback> CheckStrengthAsync(string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItWebApp.PasswordStrengthService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItWebApp.PasswordStrengthService.IService1>, TryItWebApp.PasswordStrengthService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TryItWebApp.PasswordStrengthService.PasswordFeedback CheckStrength(string password) {
            return base.Channel.CheckStrength(password);
        }
        
        public System.Threading.Tasks.Task<TryItWebApp.PasswordStrengthService.PasswordFeedback> CheckStrengthAsync(string password) {
            return base.Channel.CheckStrengthAsync(password);
        }
    }
}
