//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItWebApp.EncryptionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EncryptionService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Encrypt", ReplyAction="http://tempuri.org/IService1/EncryptResponse")]
        string Encrypt(string input, int shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Encrypt", ReplyAction="http://tempuri.org/IService1/EncryptResponse")]
        System.Threading.Tasks.Task<string> EncryptAsync(string input, int shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Decrypt", ReplyAction="http://tempuri.org/IService1/DecryptResponse")]
        string Decrypt(string input, int shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Decrypt", ReplyAction="http://tempuri.org/IService1/DecryptResponse")]
        System.Threading.Tasks.Task<string> DecryptAsync(string input, int shift);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItWebApp.EncryptionService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItWebApp.EncryptionService.IService1>, TryItWebApp.EncryptionService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Encrypt(string input, int shift) {
            return base.Channel.Encrypt(input, shift);
        }
        
        public System.Threading.Tasks.Task<string> EncryptAsync(string input, int shift) {
            return base.Channel.EncryptAsync(input, shift);
        }
        
        public string Decrypt(string input, int shift) {
            return base.Channel.Decrypt(input, shift);
        }
        
        public System.Threading.Tasks.Task<string> DecryptAsync(string input, int shift) {
            return base.Channel.DecryptAsync(input, shift);
        }
    }
}
